apiVersion: networking.istio.io/v1beta1
kind: VirtualService
spec:
  hosts:
  - backend
  http:
  - fault:
      delay:
        fixedDelay: 5s
        percentage:
          value: 100
    match:
    - uri:
        prefix: "/delay"
    route:
    - destination:
        host: backend.default.svc.cluster.local
        
  - fault:
      abort:
        httpStatus: 403
        percentage:
          value: 100
    match:
    - uri:
        prefix: "/fault"
    route:
    - destination:
        host: backend.default.svc.cluster.local

  - route:
    - destination:
        host: backend.default.svc.cluster.local

