apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  namespace: default
  name: customers
spec:
  selector:
    matchLabels:
      app: customers
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - "cluster.local/ns/default/sa/payments"
        - "cluster.local/ns/default/sa/orders"
  - to:
    - operation:
        methods: ["GET"]
        paths: ["/api"]
